name:                MusiCompoNator
version:             0.1.0.0
github:              "furryRogue/MusiCompoNator"
license:             BSD3
author:              "Joachim Tilsted Kristensen"
maintainer:          "tilsted@di.ku.dk"
copyright:           "2019 Joachim Tilsted Kristensen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata
synopsis:    This is a combinator library for composing music.
category:    Music composition.
description: Please consult ./README.md

dependencies:
- base >= 4.7 && < 5
- zmidi-core

library:
  source-dirs: src

tests:
  MusiCompoNator-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    dependencies:
    - MusiCompoNator
    - process