name:                MC
version:             0.1.0.0
license:             BSD3
author:              "Joachim Tilsted Kristensen"
maintainer:          "tilsted@di.ku.dk"
copyright:           "2019 Joachim Tilsted Kristensen"

extra-source-files:
- README.md

# Metadata
synopsis:    A combinator library for composing music.
category:    Music composition.
description: MC is a declarative eDSL for computer aided Music Composition.
             In which concepts such as harmony and rhythm are separated as
             different concerns, and phrases may be expressed abstractly.

dependencies:
- base >= 4.7 && < 5
- zmidi-core >= 0.9 && < 1
- mtl

library:
  source-dirs: src

tests:
  MusiCompoNator-test:
    main:        Songbook.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    dependencies:
    - MC
